config/routes.rb

Oadr::Application.routes.draw do

  match "/about", to: "static_pages#about"


  match "/api/createReport", to: "apis#create_report", via: :post
  match "/api/showReports", to: "apis#showReports", via: :get

  match "/api/createEvent", to: "apis#create_event", via: :post
  match "/api/showEvents", to: "apis#show_events", via: :get
  match "/api/cancelEvent", to: "apis#cancel_event", via: :post


  resources :emix_units

  resources :reports
  resources :opt_schedules, only: [:show, :destroy]

  resources :report_requests, only: [:show, :destroy, :update, :edit, :index] do
    member do
      get 'list_rids', to: :list_rids, as: 'list_rids'
      post 'save_rids', to: :save_rids, as: 'save_rids'
    end
  end

  resources :create_reports, except: [:new, :create] do
    resources :report_requests, only: [:new, :create]

    member do
      put 'send_to_ven', to: :send_to_ven, as: 'send_to_ven'
      put 'cancel_create_report', to: :cancel_create_report, as: 'cancel_create_report'
    end
  end

  resources :vtn_parameters, only: [:index, :update, :create, :show]

  resources :schedules, except: [:edit]
  match "dashboard", to: "dashboard#dashboard"

  resources :event_responses, only: [:create]

  resources :event_signal_intervals, except: [:new, :create]

  resources :event_signals do
    member do
    end

    resources :event_signal_intervals, only: [:new, :create, :update]
  end

  resources :event_signals

  resources :events, except: [:edit] do
    member do
      put 'add_parties', to: :add_parties, as: "add_parties"
      put 'remove_parties', to: :remove_parties, as: "remove_parties"

      put 'add_vens', to: :add_vens, as: "add_vens"
      put 'remove_vens', to: :remove_vens, as: "remove_vens"

      put 'add_groups', to: :add_groups, as: "add_groups"
      put 'remove_groups', to: :remove_groups, as: "remove_groups"

      put 'add_resources', to: :add_resources, as: "add_resources"
      put 'remove_resources', to: :remove_resources, as: "remove_resources"

      put 'cancel', to: :cancel, as: "cancel"
      put 'publish', to: :publish, as: "publish"
    end

    resources :event_signals#, only: [:new, :create, :update]
  end

  resources :market_contexts, except: [:new, :edit] do
    member do
      post 'subscribe/:ven_id', to: :subscribe, as: "subscribe"
      post 'unsubscribe/:ven_id', to: :unsubscribe, as: "unsubscribe"
    end
  end

  resources :groups do
    member do
      put 'add_members', to: :add_members, as: "add_members"
      put 'remove_members', to: :remove_members, as: "remove_members"
    end

  end

  resources :groups, except: [:new]

  resources :market_contexts, except: [:new, :edit]
  
  resources :resources

  match "vens/all", to: "vens#all"

  resources :vens, except: [:edit] do
    resources :resources

    resources :create_reports, only: [:new, :create]

    member do
      put 'reregister', to: :reregister, as: 'reregister'
      put 'cancel_registration', to: :cancel_registration, as: 'cancel_registration'
      put 'clear_registration', to: :clear_registration, as: 'clear_registration'
  	end
  end

  resources :resource_types, except: [:new, :edit]



  match "accounts/:id/admin", to: 'accounts#admin', via: :put, as: "accounts_admin"


  resources :accounts, except: [:edit] do
    resources :vens
  end

  resources :sessions, only: [:create]


  match '/login',  to: 'sessions#new', via: :get
  match '/login',  to: 'sessions#create', via: :post
  match '/gettoken',  to: 'sessions#get_token', via: :post

  match '/logout', to: 'sessions#destroy', via: :delete

  root :to => 'sessions#new'

  match "/eventfeed" => "eventfeed#index"

  match "/eventfeed/:ven_name" => "eventfeed#events"

  match "testcaseprompts" => "test_case_prompts#index"
  match "testcaseprompts/:id/execute" => "test_case_prompts#execute", via: :post, as: "testcaseprompts_execute"

  match "testcaseprompts/clear_events" => "test_case_prompts#clear_events", via: :post, as: "testcaseprompts_clear_events"

  match "/OpenADR2/Simple/2.0b/OadrPoll", to: "oadr20b#poll", via: [:post, :get], as: "oadr20b_poll"
  match "/OpenADR2/Simple/2.0b/EiRegisterParty", to: "oadr20b#register", via: [:post], as: "oadr20b_register"
  match "/OpenADR2/Simple/2.0b/EiOpt", to: "oadr20b#opt", via: [:post], as: "oadr20b_opt"

  match "/OpenADR2/Simple/2.0b/EiEvent", to: "oadr20b#event", via: [:post], as: "oadr20b_event"

  match "/OpenADR2/Simple/2.0b/EiReport", to: "oadr20b#report", via: [:post], as: "oadr20b_report"

  match "/OpenADR2/Simple/EiEvent", to: "oadr20a#event", via: [:post, :get], as: "oadr20a_event"











end

app/views/resources/edit.html.erb
<%= generate_notice notice %>
<%= generate_error flash[:error] %>

<%= generate_errors @resource, "prohibited this VEN from being saved:" %>

<%= generate_edit_columns @resource, Resource,
    "Resource Identification",
    [:name, :ven_id, :resource_type_id],
    "Update Identification"
%>

<%= generate_edit_columns @resource, Resource,
    "Location",
    [:address, :state, :zip, :geospatial_location, :grid_electrical_coordinates, nil],
    "Update Identification"
%>

<%= generate_edit_columns @resource, Resource,
    "Capabilities",
    [:shed_capability, :ramp_period, :recovery_period],
    "Update Capabilities"
%>

<%= link_to "Back to VEN", ven_path(@resource.ven), class: 'btn btn-default' %>

app/views/resources/index.html.erb
<%= generate_error flash[:error] %>
<%= generate_notice flash[:notice] %>

<%= generate_list(@resources, Resource, "Resources",
    [:name, :address, :state, :ven_id],
    new_resource_path,
    "Create Resource") %>

app/views/resources/new.html.erb
<%= generate_notice notice %>
<%= generate_error flash[:error] %>

<%= generate_errors @resource, "prohibited this Resource from being created:" %>

<%= generate_edit_columns [@ven, @resource], Resource,
    "Create Resource for VEN " + @ven.name,
    [:name, :ven_id, nil, :address, :state, :zip, :resource_type_id, nil, nil],
    "Create Resource"
%>
<%= link_to "Back to VEN #{@ven.name}", ven_path(@ven), class: "btn btn-default" %>